# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.1.3, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Entity
    from ._models_py3 import Error
    from ._models_py3 import Feature
    from ._models_py3 import FeatureCollection
    from ._models_py3 import Layer
    from ._models_py3 import LayerQuery
    from ._models_py3 import LineString
    from ._models_py3 import MultiLineString
    from ._models_py3 import MultiPoint
    from ._models_py3 import MultiPolygon
    from ._models_py3 import Point
    from ._models_py3 import Polygon
except (SyntaxError, ImportError):
    from ._models import Entity  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import Feature  # type: ignore
    from ._models import FeatureCollection  # type: ignore
    from ._models import Layer  # type: ignore
    from ._models import LayerQuery  # type: ignore
    from ._models import LineString  # type: ignore
    from ._models import MultiLineString  # type: ignore
    from ._models import MultiPoint  # type: ignore
    from ._models import MultiPolygon  # type: ignore
    from ._models import Point  # type: ignore
    from ._models import Polygon  # type: ignore

__all__ = [
    'Entity',
    'Error',
    'Feature',
    'FeatureCollection',
    'Layer',
    'LayerQuery',
    'LineString',
    'MultiLineString',
    'MultiPoint',
    'MultiPolygon',
    'Point',
    'Polygon',
]
